language: java
sudo: false
services:
  - docker
jdk:
  - oraclejdk8
script:
# - mvn clean install
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - mvn -f exchange-monitor-app/pom.xml clean package docker:build -DpushImage