language: java
sudo: false
services:
  - docker
jdk:
  - oraclejdk8
script:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - mvn -f exchange-monitor-app/pom.xml docker:build -DpushImage
notifications:
  slack: $SLACK_TOKEN